# Generated by Django 5.1.10 on 2026-07-30 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entry_date', models.DateField()),
                ('image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeline_entry',
                'ordering': ('-entry_date',),
                'indexes': [models.Index(fields=['is_published', 'entry_date'], name='timeline_en_is_publ_0cf487_idx')],
            },
        ),
    ]
