# Generated by Django 5.1.10 on 2026-07-31 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_committee_committeemembership_and_more'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='membership.committee'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
