# Generated by Django 5.1.10 on 2026-07-23 08:57

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AssistantInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_interaction',
                'indexes': [models.Index(fields=['created_at'], name='assistant_i_created_1ca290_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentversion')),
            ],
            options={
                'db_table': 'assistant_document_chunk',
                'indexes': [models.Index(fields=['document_version'], name='assistant_d_documen_7f808c_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_version', 'chunk_index'), name='uniq_chunk_index_per_version')],
            },
        ),
    ]
