from django.urls import path

from apps.membership.presentation.views import (
    AdminCreateMemberView,
    AdminEraseMemberView,
    AdminSetMemberActiveView,
    AdminUpdateMemberContactView,
    CommitteeListCreateView,
    CommitteeMemberRemoveView,
    CommitteeMembersView,
    DuesRecordView,
    GuardianConsentView,
    GuardianLinkView,
    MemberDirectoryView,
    MembershipAdminListView,
    MembershipTierListCreateView,
    MembershipTransitionView,
    MyGuardianRelationshipsView,
    MyMembershipView,
    MyProfilePhotoView,
    MyProfileView,
    PublicCommitteeRosterView,
    PublicRosterView,
    TierAssignmentView,
)

urlpatterns = [
    path("me/", MyMembershipView.as_view(), name="membership-me"),
    path("directory/", MemberDirectoryView.as_view(), name="membership-directory"),
    path("admin/", MembershipAdminListView.as_view(), name="membership-admin-list"),
    path("admin/create/", AdminCreateMemberView.as_view(), name="membership-admin-create"),
    path(
        "admin/contact/",
        AdminUpdateMemberContactView.as_view(),
        name="membership-admin-contact",
    ),
    path(
        "admin/active/",
        AdminSetMemberActiveView.as_view(),
        name="membership-admin-active",
    ),
    path(
        "admin/erase/",
        AdminEraseMemberView.as_view(),
        name="membership-admin-erase",
    ),
    path("profile/me/", MyProfileView.as_view(), name="membership-profile-me"),
    path("profile/photo/", MyProfilePhotoView.as_view(), name="membership-profile-photo"),
    path("profile/public/", PublicRosterView.as_view(), name="membership-profile-public"),
    path("committees/", CommitteeListCreateView.as_view(), name="membership-committees"),
    path(
        "committees/<uuid:committee_id>/members/",
        CommitteeMembersView.as_view(),
        name="membership-committee-members",
    ),
    path(
        "committees/<uuid:committee_id>/members/<uuid:user_id>/remove/",
        CommitteeMemberRemoveView.as_view(),
        name="membership-committee-member-remove",
    ),
    path(
        "committees/<uuid:committee_id>/roster/",
        PublicCommitteeRosterView.as_view(),
        name="membership-committee-public-roster",
    ),
    path("transitions/", MembershipTransitionView.as_view(), name="membership-transition"),
    path("guardians/link/", GuardianLinkView.as_view(), name="membership-guardians-link"),
    path("guardians/consent/", GuardianConsentView.as_view(), name="membership-guardians-consent"),
    path("guardians/me/", MyGuardianRelationshipsView.as_view(), name="membership-guardians-me"),
    path("tiers/", MembershipTierListCreateView.as_view(), name="membership-tiers"),
    path("tiers/assign/", TierAssignmentView.as_view(), name="membership-tiers-assign"),
    path("dues/record/", DuesRecordView.as_view(), name="membership-dues-record"),
]
