REG_STATUS_REGISTERED = "registered"
REG_STATUS_CANCELLED = "cancelled"
REG_STATUS_ATTENDED = "attended"

REGISTRATION_STATUS_CHOICES = (
    (REG_STATUS_REGISTERED, "Registered"),
    (REG_STATUS_CANCELLED, "Cancelled"),
    (REG_STATUS_ATTENDED, "Attended"),
)
