RELATIONSHIP_PARENT = "parent"
RELATIONSHIP_LEGAL_GUARDIAN = "legal_guardian"
RELATIONSHIP_OTHER = "other"

RELATIONSHIP_CHOICES = (
    (RELATIONSHIP_PARENT, "Parent"),
    (RELATIONSHIP_LEGAL_GUARDIAN, "Legal Guardian"),
    (RELATIONSHIP_OTHER, "Other"),
)
