STATUS_PENDING = "pending"
STATUS_ACTIVE = "active"
STATUS_SUSPENDED = "suspended"
STATUS_EXPIRED = "expired"
STATUS_CANCELLED = "cancelled"

STATUS_CHOICES = (
    (STATUS_PENDING, "Pending"),
    (STATUS_ACTIVE, "Active"),
    (STATUS_SUSPENDED, "Suspended"),
    (STATUS_EXPIRED, "Expired"),
    (STATUS_CANCELLED, "Cancelled"),
)

ALLOWED_TRANSITIONS = {
    STATUS_PENDING: {STATUS_ACTIVE, STATUS_CANCELLED},
    STATUS_ACTIVE: {STATUS_SUSPENDED, STATUS_EXPIRED, STATUS_CANCELLED},
    STATUS_SUSPENDED: {STATUS_ACTIVE, STATUS_EXPIRED, STATUS_CANCELLED},
    STATUS_EXPIRED: {STATUS_ACTIVE, STATUS_CANCELLED},
    STATUS_CANCELLED: set(),
}
