# Generated by Django 5.1.10 on 2026-07-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_9a4505_idx',
            old_name='notificatio_status_4ff4fc_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_channel_1d6e5f_idx',
            old_name='notificatio_channel_4cba03_idx',
        ),
    ]
