# Generated by Django 5.1.10 on 2026-07-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_publ_415ff6_idx',
            old_name='events_even_is_publ_6222ec_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_created_52c227_idx',
            old_name='events_even_created_33a3ab_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='events_regi_status_d86c95_idx',
            old_name='events_regi_status_66f175_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
