# Generated by Django 5.1.10 on 2026-07-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_even_is_publ_6222ec_idx_events_even_is_publ_415ff6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='registered', max_length=32),
        ),
    ]
