# Generated by Django 5.1.10 on 2026-07-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membership',
            new_name='membership__status_342adb_idx',
            old_name='membership__status_85f6ce_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='membership__created_d36cd2_idx',
            old_name='membership__created_157088_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatustransition',
            new_name='membership__changed_61f572_idx',
            old_name='membership__changed_2d8fd8_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipstatustransition',
            new_name='membership__from_st_4fe35d_idx',
            old_name='membership__from_st_3150c8_idx',
        ),
    ]
