# Generated by Django 5.1.10 on 2026-07-21 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_rename_membership__status_85f6ce_idx_membership__status_342adb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('legal_guardian', 'Legal Guardian'), ('other', 'Other')], max_length=32)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships_as_child', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships_as_guardian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_guardian_relationship',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('price_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='GBP', max_length=8)),
                ('billing_period_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'membership_tier',
                'indexes': [models.Index(fields=['is_active'], name='membership__is_acti_cb9a03_idx')],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='membership.membershiptier'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['expires_at'], name='membership__expires_e9e331_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['child'], name='membership__child_i_72fca5_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['guardian'], name='membership__guardia_249b53_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelationship',
            constraint=models.UniqueConstraint(fields=('guardian', 'child'), name='uniq_guardian_child'),
        ),
    ]
