# Generated by Django 5.1.10 on 2026-07-31 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_memberprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membership_committee',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('Advisors', 'Advisors'), ('President', 'President'), ('Senior Vice President', 'Senior Vice President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Joint General Secretary', 'Joint General Secretary'), ('Assistant General Secretary', 'Assistant General Secretary'), ('Organizing Secretary', 'Organizing Secretary'), ('Assistant Organizing Secretary', 'Assistant Organizing Secretary'), ('Publicity Secretary', 'Publicity Secretary'), ('Sports Secretary', 'Sports Secretary'), ('Honorable Member', 'Honorable Member'), ('Events Organizer', 'Events Organizer'), ('General Member', 'General Member')], max_length=128)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'membership_committee_membership',
                'ordering': ('display_order',),
            },
        ),
        migrations.RemoveIndex(
            model_name='memberprofile',
            name='membership__public__a9e9da_idx',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='position',
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['public_consent'], name='membership__public__556f65_idx'),
        ),
        migrations.AddField(
            model_name='committee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='membership.committee'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['starts_at', 'ends_at'], name='membership__starts__515d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee', 'display_order'], name='membership__committ_7cd728_idx'),
        ),
        migrations.AddConstraint(
            model_name='committeemembership',
            constraint=models.UniqueConstraint(fields=('committee', 'user'), name='uniq_committee_member'),
        ),
    ]
