# Generated by Django 5.1.10 on 2026-07-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_is_acti_d6d154_idx',
            old_name='shop_produc_is_acti_8d609d_idx',
        ),
        migrations.RenameIndex(
            model_name='shoporder',
            new_name='shop_order_status_700268_idx',
            old_name='shop_order_status_8b37aa_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
