# Generated by Django 5.1.10 on 2026-07-22 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_produc_is_acti_8d609d_idx_shop_produc_is_acti_d6d154_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='payment_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
