# Generated by Django 5.1.10 on 2026-07-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoporder_payment_reference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoporderitem',
            name='uniq_order_product_item',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='size',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='shoporderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'size'), name='uniq_order_product_size_item'),
        ),
    ]
