# Generated by Django 5.1.10 on 2026-07-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='finance_led_entry_t_085ea6_idx',
            old_name='finance_led_entry_t_914952_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='finance_led_currenc_947ff9_idx',
            old_name='finance_led_currency_720267_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='finance_pay_status_b631de_idx',
            old_name='finance_pay_status_8f1d6f_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhookevent',
            new_name='finance_pay_provide_ba3d2a_idx',
            old_name='finance_pay_provider_eb16f8_idx',
        ),
    ]
