# Generated by Django 5.1.10 on 2026-07-28 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_finance_led_entry_t_914952_idx_finance_led_entry_t_085ea6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=32, unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='GBP', max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pdf_file_key', models.CharField(max_length=512)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='finance.ledgerentry')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_receipt',
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='finance_rec_recipie_ff19a7_idx')],
            },
        ),
    ]
