# Generated by Django 5.1.10 on 2026-07-28 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('member', 'Member'), ('staff', 'Staff')], default='member', max_length=16)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('quorum', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_poll',
            },
        ),
        migrations.CreateModel(
            name='PollBallotReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_receipts', to='voting.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_ballot_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_poll_ballot_receipt',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.poll')),
            ],
            options={
                'db_table': 'voting_poll_option',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.poll')),
            ],
            options={
                'db_table': 'voting_poll_vote',
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['visibility', 'opens_at'], name='voting_poll_visibil_e5d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['closes_at'], name='voting_poll_closes__f951d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pollballotreceipt',
            index=models.Index(fields=['poll'], name='voting_poll_poll_id_66dfc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollballotreceipt',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='uniq_poll_ballot_per_user'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'option'], name='voting_poll_poll_id_082742_idx'),
        ),
    ]
