# Generated by Django 5.1.10 on 2026-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='position',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='polloption',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
