# Generated by Django 5.1.10 on 2026-07-31 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_polloption_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voting_method',
            field=models.CharField(choices=[('plurality', 'Plurality (most votes wins)'), ('ranked_choice', 'Ranked-choice (instant runoff)')], default='plurality', max_length=16),
        ),
        migrations.CreateModel(
            name='PollRankedVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot_token', models.UUIDField(default=uuid.uuid4)),
                ('rank', models.PositiveIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranked_votes', to='voting.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranked_votes', to='voting.poll')),
            ],
            options={
                'db_table': 'voting_poll_ranked_vote',
                'indexes': [models.Index(fields=['poll', 'ballot_token'], name='voting_poll_poll_id_8ad307_idx')],
                'constraints': [models.UniqueConstraint(fields=('ballot_token', 'rank'), name='uniq_ranked_ballot_rank'), models.UniqueConstraint(fields=('ballot_token', 'option'), name='uniq_ranked_ballot_option')],
            },
        ),
    ]
