# Generated by Django 5.1.10 on 2026-07-22 23:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('policy', 'Policy'), ('minutes', 'Minutes'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('member', 'Member'), ('staff', 'Staff')], default='member', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('file_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='pending', max_length=16)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_error', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document_version',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visibility', 'category'], name='documents_d_visibil_b3198c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='documents_d_documen_3e0c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
    ]
