# Generated by Django 5.1.10 on 2026-07-21 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_email_verification_token',
            },
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='identity_ro_code_a0a823_idx',
            old_name='identity_rol_code_61b11d_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='identity_ro_is_acti_664a95_idx',
            old_name='identity_rol_is_acti_12e2d6_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='identity_us_created_7cdce4_idx',
            old_name='identity_use_created_8642cf_idx',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='identity_em_token_c1f412_idx'),
        ),
    ]
