# Generated by Django 5.1.10 on 2026-07-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
